---
title: "Proj2 SMART 2 Part 2"
author: "Sabina Shahbazzade"
date: "11/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(ggplot2)
```

```{r read, echo=FALSE, include = TRUE}
athlete_events = read.csv("athlete_events.csv")
#str(athlete_events)
```

```{r NAs, echo=FALSE}
# omitting NAs leaves only athletes that won medals
summer_events = na.omit(athlete_events[athlete_events$Season == 'Summer',])

# keeping NAs for analysis of winners and losers
summer_w_NAs = athlete_events[athlete_events$Season=='Summer',]

```


#### 4.	SMART 2 - 
### Can we draw any correlations between gender distribution and wins? 
```{r Pie_Chart}

#Pie Chart of distribution of medals won by Male 

labels <-  c("Gold","Silver","Bronze")
piepercent_m<- paste(round(100*Total_Medals_Male/sum(Total_Medals_Male), 1), "%", sep = "")

# Plot the chart.
pie(Total_Medals_Male, labels = piepercent_m, main = "Distribution of all medals won by Male athletes",col = rainbow(length(Total_Medals_Male)))
legend("topright", c("Gold","Silver","Bronze"), cex = 0.8,
   fill = rainbow(length(Total_Medals_Male)))

```

```{r}
# Subquestion 3: Who (female or male) won more (gold, silver, bronze)?

Medals <- c("Gold", "Silver", "Bronze")
Female_Percentage <- c(piepercent_f)
Male_Percentage <- c(piepercent_m)
f_m_data <- data.frame(Medals, Female_Percentage, Male_Percentage)
f_m_data

```

```{r}
# Table 1 - The number of male athletes from 2000 to 2018 by country
# years from 2000 -2010, country, number of males
male_won_medals <- subset(summer_events, Sex == 'M')
library(data.table)
male_won_medals <- as.data.table(male_won_medals)
table1 <- subset(male_won_medals, select = c("Year", "NOC"), Year>=2000)
tb1<-table1 %>% count(Year, NOC)
tb1 %>% arrange(desc(n))

```

```{r}
# Table 2 - The number of male athletes from 2000 to 2018 by country
# years from 2000 -2010, country, number of females
female_won_medals <- subset(summer_events, Sex == 'F')
female_won_medals <- as.data.table(female_won_medals)
table2 <- subset(female_won_medals, select = c("Year", "NOC"), Year>=2000)
tb2<-table2 %>% count(Year, NOC)
tb2 %>% arrange(desc(n))
```